export const SAMPLE_BOUNTIES = [
  {
    id: 'sample-bounty-1',
    title: 'Real-time Video RAG Pipeline',
    problem_description: 'We need a low-latency pipeline to process live video streams and perform RAG against a temporal vector database. The goal is to answer questions about events happening in the video under 200ms.',
    expected_output: 'A working Docker container and Github repo with a FastAPI endpoint.',
    reward_inr: 50000,
    skills_needed: ['PyTorch', 'FFmpeg', 'Pinecone', 'FastAPI'],
    status: 'open',
    deadline: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    company: {
      company_name: 'NeuroCore AI Labs',
      logo_url: null
    }
  },
  {
    id: 'sample-bounty-2',
    title: 'LLM Hallucination Guardrail',
    problem_description: 'Develop a specialized guardrail model to detect and prevent numerical hallucinations in financial advice generated by LLMs. Must achieve 99% precision on interest rate queries.',
    expected_output: 'Evaluation report and a Python library for pre/post-processing.',
    reward_inr: 75000,
    skills_needed: ['LangChain', 'OpenAI', 'Evaluation Frameworks'],
    status: 'open',
    deadline: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    company: {
      company_name: 'Nexus AI Solutions',
      logo_url: null
    }
  },
  {
    id: 'sample-bounty-3',
    title: 'Edge Device Quantization',
    problem_description: 'Shrink Llama-3 8B to under 2GB VRAM while maintaining 90% accuracy on MMLU. Focus on specialized quantization techniques like GGUF or AWQ.',
    expected_output: 'Quantization script and benchmark report.',
    reward_inr: 35000,
    skills_needed: ['CUDA', 'C++', 'Python'],
    status: 'open',
    deadline: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    company: {
      company_name: 'Silicon Neural',
      logo_url: null
    }
  }
]

export const SAMPLE_JOBS = [
  {
    id: 'sample-job-1',
    title: 'Senior AI Research Engineer',
    description: 'Join our Core AI Team to develop next-generation multi-modal agents. You will be responsible for scaling our training infrastructure using Slurm and Kubernetes.',
    engagement_type: 'full-time',
    budget_min_inr: 250000,
    budget_max_inr: 450000,
    min_neuron_score: 85,
    skills_required: ['CUDA', 'PyTorch', 'Distributed Training'],
    created_at: new Date().toISOString(),
    company: {
      company_name: 'NeuroCore AI Labs',
      logo_url: null
    }
  },
  {
    id: 'sample-job-2',
    title: 'Fullstack AI Product Engineer',
    description: 'Help us build the most intuitive interface for AI model orchestration. Bridging the gap between complex Python backends and sleek React frontends.',
    engagement_type: 'contract',
    budget_min_inr: 150000,
    budget_max_inr: 300000,
    min_neuron_score: 70,
    skills_required: ['Next.js', 'FastAPI', 'LangChain'],
    created_at: new Date().toISOString(),
    company: {
      company_name: 'Nexus AI Solutions',
      logo_url: null
    }
  },
  {
    id: 'sample-job-3',
    title: 'Agentic Workflow Architect',
    description: 'Design and implement complex multi-agent workflows for enterprise automation. Experience with AutoGen or CrewAI is highly desirable.',
    engagement_type: 'project',
    budget_min_inr: 120000,
    budget_max_inr: 200000,
    min_neuron_score: 80,
    skills_required: ['AutoGen', 'Python', 'Agentic Design Patterns'],
    created_at: new Date().toISOString(),
    company: {
      company_name: 'Silicon Neural',
      logo_url: null
    }
  }
]
