import { createClient } from '@supabase/supabase-js'
import fs from 'fs'

// Read env from .env.local
const envFile = fs.readFileSync('.env.local', 'utf8')
const env = Object.fromEntries(
  envFile.split('\n')
    .filter(line => line.includes('='))
    .map(line => {
      const [k, ...v] = line.split('=')
      return [k.trim(), v.join('=').trim().replace(/^"(.*)"$/, '$1')]
    })
)

const supabase = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY)

async function seed() {
  console.log('Fetching companies...')
  const { data: companies } = await supabase.from('companies').select('*')
  
  if (!companies || companies.length === 0) {
    console.error('No companies found. Create one first.')
    return
  }

  const companyId = companies[0].id
  console.log(`Using company: ${companies[0].company_name} (${companyId})`)

  const sampleBounties = [
    {
      company_id: companyId,
      title: 'Real-time Video RAG Pipeline',
      problem_description: 'We need a low-latency pipeline to process live video streams and perform RAG against a temporal vector database. The goal is to answer questions about events happening in the video under 200ms.',
      expected_output: 'A working Docker container and Github repo with a FastAPI endpoint.',
      reward_inr: 50000,
      skills_needed: ['PyTorch', 'FFmpeg', 'Pinecone', 'FastAPI'],
      status: 'open',
      deadline: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
      company_id: companyId,
      title: 'LLM Hallucination Guardrail for Fintech',
      problem_description: 'Develop a specialized guardrail model to detect and prevent numerical hallucinations in financial advice generated by LLMs. Must achieve 99% precision on interest rate queries.',
      expected_output: 'Evaluation report and a Python library for pre/post-processing.',
      reward_inr: 75000,
      skills_needed: ['LangChain', 'OpenAI', 'Evaluation Frameworks'],
      status: 'open',
      deadline: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString()
    }
  ]

  console.log('Inserting bounties...')
  const { error } = await supabase.from('bounties').insert(sampleBounties)
  
  if (error) console.error('Error seeding:', error)
  else console.log('Successfully seeded premium bounties!')
}

seed()
